# Generated by Django 4.2.2 on 2023-06-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
    ]
