# Generated by Django 4.2.2 on 2023-06-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_first_name_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.CharField(default='', max_length=100),
        ),
    ]
