# Generated by Django 4.2.2 on 2023-06-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_team_captain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Tournament',
            new_name='tournament',
        ),
    ]
