# Generated by Django 4.2.2 on 2023-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schedule_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_table',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
