# Generated by Django 4.2.2 on 2023-07-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schedule_table_is_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_batters', models.CharField(max_length=1000)),
                ('team1_balls', models.CharField(max_length=1000)),
                ('team1_fours', models.CharField(max_length=1000)),
                ('team1_sixes', models.CharField(max_length=1000)),
                ('team1_strike_rates', models.CharField(max_length=1000)),
                ('team2_batters', models.CharField(max_length=1000)),
                ('team2_balls', models.CharField(max_length=1000)),
                ('team2_fours', models.CharField(max_length=1000)),
                ('team2_sixes', models.CharField(max_length=1000)),
                ('team2_strike_rates', models.CharField(max_length=1000)),
                ('team1_bowlers', models.CharField(max_length=1000)),
                ('team1_overs', models.CharField(max_length=1000)),
                ('team1_runs', models.CharField(max_length=1000)),
                ('team1_wickets', models.CharField(max_length=1000)),
                ('team1_economy', models.CharField(max_length=1000)),
                ('team2_bowlers', models.CharField(max_length=1000)),
                ('team2_overs', models.CharField(max_length=1000)),
                ('team2_runs', models.CharField(max_length=1000)),
                ('team2_wickets', models.CharField(max_length=1000)),
                ('team2_economy', models.CharField(max_length=1000)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.schedule_table')),
            ],
        ),
    ]
