# Generated by Django 4.2.2 on 2023-07-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='match',
        ),
    ]
