# Generated by Django 4.2.2 on 2023-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='player',
            name='no_fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='no_sixes',
            field=models.IntegerField(default=0),
        ),
    ]
