# Generated by Django 4.2.2 on 2023-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_match_options_player_no_fours_player_no_sixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_total_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_total_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_total_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_total_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
