# Generated by Django 4.2.2 on 2023-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_match_team1_total_runs_match_team1_total_wickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_total_overs',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_total_overs',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_5_matches',
            field=models.CharField(default='', max_length=5),
        ),
    ]
